spring.datasource.url=jdbc:sqlserver://sql-java-aks-2026.database.windows.net:1433;databaseName=employee-db;encrypt=true;trustServerCertificate=false;authentication=ActiveDirectoryDefault

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true