name: Employee Management CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

  backend-build:
    runs-on: ubuntu-latest
    needs: checkout

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Run tests
        run: ./mvnw clean test

      - name: Build backend JAR
        run: ./mvnw package -DskipTests

  frontend-build:
    runs-on: ubuntu-latest
    needs: checkout

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run lint
        run: npm run lint

      - name: Build frontend
        run: npm run build

  backend-docker:
    runs-on: ubuntu-latest
    needs: backend-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build backend Docker image
        run: docker build -t acrjavaaks2026.azurecr.io/employee-backend:1.0.0 ./backend

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name acrjavaaks2026

      - name: Push backend image
        run: docker push acrjavaaks2026.azurecr.io/employee-backend:1.0.0


  frontend-docker:
    runs-on: ubuntu-latest
    needs: frontend-build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build frontend Docker image
        run: docker build -t acrjavaaks2026.azurecr.io/employee-frontend:1.0.0 ./frontend

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR
        run: az acr login --name acrjavaaks2026

      - name: Push frontend image
        run: docker push acrjavaaks2026.azurecr.io/employee-frontend:1.0.0